using Microsoft.EntityFrameworkCore;
using PetroProcure.AI;
using PetroProcure.Infrastructure.Persistence.Configurations;

namespace PetroProcure.Infrastructure.Persistence.Configurations.Ai;

internal static class AiConfigurations
{
    public static void Configure(ModelBuilder b) { }
}
internal sealed class AiProviderConfiguration : IEntityTypeConfiguration<AiProvider> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiProvider> b) { b.ToTable("AiProviders", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.ProviderType).HasMaxLength(100); b.Property(x => x.BaseUrl).HasMaxLength(1000); } }
internal sealed class AiModelConfiguration : IEntityTypeConfiguration<AiModel> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiModel> b) { b.ToTable("AiModels", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.ModelIdentifier).HasMaxLength(300); } }
internal sealed class AiAgentDefinitionConfiguration : IEntityTypeConfiguration<AiAgentDefinition> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiAgentDefinition> b) { b.ToTable("AiAgentDefinitions", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Capability).HasMaxLength(200); } }
internal sealed class AiPromptTemplateConfiguration : IEntityTypeConfiguration<AiPromptTemplate> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiPromptTemplate> b) { b.ToTable("AiPromptTemplates", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Name).HasMaxLength(200); b.Property(x => x.Template).HasMaxLength(8000); } }
internal sealed class ProcurementRuleConfiguration : IEntityTypeConfiguration<ProcurementRule> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<ProcurementRule> b) { b.ToTable("ProcurementRules", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Title).HasMaxLength(500); b.HasMany(x => x.Clauses).WithOne().HasForeignKey(x => x.ProcurementRuleId); b.Navigation(x => x.Clauses).UsePropertyAccessMode(PropertyAccessMode.Field); } }
internal sealed class ProcurementRuleClauseConfiguration : IEntityTypeConfiguration<ProcurementRuleClause> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<ProcurementRuleClause> b) { b.ToTable("ProcurementRuleClauses", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.ConditionType).HasMaxLength(100); b.Property(x => x.ConditionValue).HasMaxLength(1000); b.Property(x => x.ConditionDescription).HasMaxLength(2000); } }
internal sealed class AiEvaluationJobConfiguration : IEntityTypeConfiguration<AiEvaluationJob> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiEvaluationJob> b) { b.ToTable("AiEvaluationJobs", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.EvaluationType).HasMaxLength(100); b.HasIndex(x => x.PurchaseFileId); } }
internal sealed class AiEvaluationResultConfiguration : IEntityTypeConfiguration<AiEvaluationResult> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiEvaluationResult> b) { b.ToTable("AiEvaluationResults", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.EvaluationType).HasMaxLength(100); b.Property(x => x.Summary).HasMaxLength(8000); b.HasMany(x => x.Findings).WithOne().HasForeignKey(x => x.EvaluationResultId); b.HasMany(x => x.Recommendations).WithOne().HasForeignKey(x => x.EvaluationResultId); b.Navigation(x => x.Findings).UsePropertyAccessMode(PropertyAccessMode.Field); b.Navigation(x => x.Recommendations).UsePropertyAccessMode(PropertyAccessMode.Field); } }
internal sealed class AiFindingConfiguration : IEntityTypeConfiguration<AiFinding> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiFinding> b) { b.ToTable("AiFindings", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Title).HasMaxLength(500); b.Property(x => x.Description).HasMaxLength(4000); b.Property(x => x.Code).HasMaxLength(200); } }
internal sealed class AiRecommendationConfiguration : IEntityTypeConfiguration<AiRecommendation> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiRecommendation> b) { b.ToTable("AiRecommendations", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Title).HasMaxLength(500); b.Property(x => x.Description).HasMaxLength(4000); } }
internal sealed class AiConversationConfiguration : IEntityTypeConfiguration<AiConversation> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiConversation> b) { b.ToTable("AiConversations", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Title).HasMaxLength(500); } }
internal sealed class AiMessageConfiguration : IEntityTypeConfiguration<AiMessage> { public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<AiMessage> b) { b.ToTable("AiMessages", DatabaseSchemas.Ai); b.ConfigureEntity(); b.Property(x => x.Role).HasMaxLength(50); b.Property(x => x.Content).HasMaxLength(8000); } }
